export const endpoints = {
  refreshToken: "some-endpoint",
  signIn: "some-endpoint",
  me: "some-endpoint",
  orders: "some-endpoint",
  customer_profiles: "some-endpoint",
  customers: "some-endpoint",
  settings: "some-endpoint",
  authSettings: "some-endpoint",
  permissions: "some-endpoint",
  permissionsLimit: "some-endpoint",
  packages: "some-endpoint",
  packageTrial: "some-endpoint",
  packageRules: "some-endpoint",
  roles: "some-endpoint",
  users: "some-endpoint",
  locations: "some-endpoint",
  timeSlots: "some-endpoint",
  cashPayments: "some-endpoint",
  referrals: "some-endpoint",
  coupons: "some-endpoint",
  scheduleOrders: "some-endpoint",
  deliveriesManual: "some-endpoint",
};
